# mkdocs.yml
site_name: "nwabel"
site_url: https://nwabel.github.io/
repo_url: https://github.com/nwabel/nwabel.github.io

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar  
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  icon: heroicons:bug-ant    # biarkan icon valid (wajib format iconify)
  favicon: assets/logoku.svg
  topbar_sections: true # NEW!
  katex_options: # optional
    macros: # example of macros
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: true 
  
nav:
  - Home: index.md
  - Blog:
      - Index: blog/index.md
      - tes1: blog/1.md
      - tes2: blog/2.md
  - Lab:
      - Index: labs/index.md
      - CVE 2015 3306: labs/CVE-2015-3306.md
      - Cryptanalysis: labs/Cryptanalysis.md
  - Materi:
      - Index: materi/index.md
      - Kriptografi Intro: materi/Kriptografi___Intro.md
      - Simetris dan Asimetris: "materi/Kriptografi___Enkripsi Simetris dan Asimetris.md"
      - asd:
          - materi/asd/index.md

markdown_extensions:
  - meta
  - attr_list
  - codehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.progressbar
  - pymdownx.tabbed
  - codehilite
  - shadcn.extensions.codexec
  - shadcn.extensions.echarts.alpha
  - fenced_code

plugins:
  - search
  - excalidraw
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
       - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  
extra_css:
  - https://unpkg.com/aos@2.3.4/dist/aos.css
  - assets/css/home.css
  - assets/css/landing.css
  - assets/css/fixes.css
  - assets/css/breadcrumbs.css
  - stylesheets/extra.css

extra_javascript:
  - assets/js/fixes.js
  - https://unpkg.com/aos@2.3.4/dist/aos.js
  - assets/js/breadcrumbs.js
  - assets/js/loGoeEnd.js
  - assets/js/mobelLg.js
  - assets/js/aosInit.js
  - assets/js/landing.js
  - assets/js/niwPost.js
  - assets/js/counter.js
