# mkdocs.yml
site_name: "nwabel"
site_url: https://nwabel.github.io/
repo_url: https://github.com/nwabel/nwabel.github.io

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar  
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  icon: heroicons:bug-ant    # biarkan icon valid (wajib format iconify)
  favicon: assets/logoku.svg
  topbar_sections: true # NEW!
  katex_options: # optional
    macros: # example of macros
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: true 
  
nav:
  - Home: index.md
  - About: about.md
  - Blog:
      - Index: Blog/index.md
      - tes1: Blog/1.md
      - tes2: Blog/2.md
  - Lab:
      - Index: Lab/index.md
      - CVE 2015 3306: Lab/CVE-2015-3306.md
      - Cryptanalysis: Lab/Cryptanalysis.md
  - Materi:
      - Index: Materi/index.md
      - Kriptografi Intro: Materi/Kriptografi___Intro.md
      - "Simetris dan Asimetris": "Materi/Kriptografi___Enkripsi Simetris dan Asimetris.md"
      - asd:
          - Materi/asd/index.md

markdown_extensions:
  - meta
  - attr_list
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.progressbar
  - pymdownx.tabbed
  - shadcn.extensions.codexec
  - shadcn.extensions.echarts.alpha
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - excalidraw
  - awesome-pages
  - roamlinks
  - mkdocs-backlinks
  - glightbox:
      touchNavigation: true
      loop: false
      zoomable: true
      draggable: true
      auto_themed: false
  
  extra_css:
  - assets/css/home.css
  - assets/css/landing.css
  - assets/css/fixes.css
  - assets/css/breadcrumbs.css
  - stylesheets/extra.css

extra_javascript:
  - assets/js/fixes.js
  - assets/js/breadcrumbs.js
  - assets/js/loGoeEnd.js
  - assets/js/mobelLg.js
  - assets/js/aosInit.js
  - assets/js/landing.js
  - assets/js/niwPost.js
  - assets/js/counter.js
