site_name: nwabel
site_url: https://nwabel.github.io
theme:
  name: terminal
  font:
    text: Aptos
  logo: assets/images/logoku.png
  favicon: assets/images/logoku.png
  features:
    - search.highlight
    - navigation.tabs
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - toc.follow 
    - toc.autohide             
    
  palette:
    #DARK MODE
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: black
      accent: red
    #LIGHT MODE
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: black
      accent: red

plugins:
  - search
  - awesome-pages
  - roamlinks
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
       - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nwabel
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/nabilsyawali/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<nabilsywl@gmail.com>

    
  consent:
    title: s
    description: >- 


      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
